#!/bin/bash

pass=`zenity --password` || exit 1;
export $(echo -n "$pass" | gnome-keyring-daemon --unlock --replace) || exit 1;

[[ -n $pass ]] && notify-send "
        Unlocked the keyring
"

unset pass
exit 0;
