FILESEXTRAPATHS:prepend := "${THISDIR}/mupen64plus-libretro:"

LIBRETRO_EXTRA_MAKEFLAGS:append = " HAVE_PARALLEL_RDP=1 HAVE_PARALLEL_RSP=1 HAVE_THR_AL=1 LLE=1 HAVE_OPENGL=1"
LIBRETRO_EXTRA_MAKEFLAGS:append:aarch64 = " HAVE_NEON=0"

